import { chromium } from 'playwright-core';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1536,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
const data=await page.evaluate(()=>{const text=document.body.innerText; const bad=['Рџ','РќР','Рђ','Р°С','СЃР','вЂ','РјВ'].filter(x=>text.includes(x)); const compare=document.querySelector('nav button:nth-child(2) svg')?.getBoundingClientRect(); return {bad,cardText:document.querySelector('.result-card')?.innerText.slice(0,260),compare:compare&&{width:compare.width,height:compare.height,top:compare.top},images:[...document.images].map(i=>[i.complete,i.naturalWidth,i.naturalHeight]),overflow:document.body.scrollWidth-innerWidth};});
if(errors.length||data.bad.length||data.images.some(x=>!x[0]||!x[1])||data.overflow>1) throw new Error(JSON.stringify({errors,data}));
console.log(JSON.stringify(data,null,2));
await page.screenshot({path:'qa-selector-encoding-fixed.png',fullPage:true});
await browser.close();