import { chromium } from 'playwright-core';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
const startCards=await page.locator('.scenario').count();
await page.getByRole('button',{name:/Знаю, куда нужен насос/}).click();
await page.getByRole('button',{name:/Котельная/}).click();
const temperature=await page.locator('input[type=number]').nth(2).inputValue();
await page.getByRole('button',{name:'Подобрать насос',exact:true}).first().click();
await page.waitForTimeout(400);
const resultCards=await page.locator('.result-card').count();
const desktopOverflow=await page.evaluate(()=>document.body.scrollWidth-innerWidth);
await page.screenshot({path:'qa-final-desktop.png',fullPage:true});
await page.getByRole('button',{name:/Подбор/}).first().click();
await page.getByRole('button',{name:/Знаю модель/}).click();
await page.locator('.model-search input').fill('RFZ-026347');
const modelMatches=await page.locator('.model-results button').count();
await page.setViewportSize({width:390,height:844});
await page.reload({waitUntil:'networkidle'});
await page.getByRole('button',{name:/Знаю, куда нужен насос/}).click();
await page.getByRole('button',{name:/Котельная/}).click();
const mobileCta=await page.locator('.mobile-select-cta').isVisible();
const mobileOverflow=await page.evaluate(()=>document.body.scrollWidth-innerWidth);
await page.screenshot({path:'qa-final-mobile.png',fullPage:true});
const report={errors,startCards,temperature,resultCards,desktopOverflow,modelMatches,mobileCta,mobileOverflow};
console.log(JSON.stringify(report,null,2));
if(errors.length||startCards!==3||temperature!=='90'||resultCards<1||desktopOverflow>1||modelMatches!==1||!mobileCta||mobileOverflow>1)throw new Error('Final selector QA failed');
await browser.close();
