import { useMemo,useRef,useState } from 'react';
import { Header,type HeaderAction } from './components/Header';
import { ModelSearchStep } from './components/ModelSearchStep';
import { PumpTypeStep } from './components/PumpTypeStep';
import { PurposeStep } from './components/PurposeStep';
import { ResultsPanel } from './components/ResultsPanel';
import { RightRail } from './components/RightRail';
import { SelectionForm } from './components/SelectionForm';
import { StartScenario } from './components/StartScenario';
import { initialContext,results as catalog } from './domain/mockData';
import { calculateResults,sortResults } from './domain/selectionEngine';
import type { PumpResult,PurposePreset,ResultTab,SelectionContext,SelectionMode,SelectorScreen,SortMode } from './domain/types';
import { readBitrixSelectorPayload } from './services/bitrixSelectorAdapter';
const loadContext=()=>{try{return JSON.parse(localStorage.getItem('apgs-selection-context')||'null') as SelectionContext|null}catch{return null}};
const loadCompared=()=>{try{return JSON.parse(localStorage.getItem('apgs-compared')||'[]') as string[]}catch{return[]}};
export default function App(){const payload=readBitrixSelectorPayload();const initial={...initialContext,...loadContext(),...payload.context};const[screen,setScreen]=useState<SelectorScreen>('start'),[mode,setMode]=useState<SelectionMode>('qh'),[draft,setDraft]=useState<SelectionContext>(initial),[context,setContext]=useState<SelectionContext>(initial),[tab,setTab]=useState<ResultTab>('recommended'),[sort,setSort]=useState<SortMode>('score'),[compared,setCompared]=useState<string[]>(loadCompared),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<HeaderAction|'details'|'assistant'|null>(null),[details,setDetails]=useState<PumpResult|null>(null);const resultsRef=useRef<HTMLElement|null>(null);const items=useMemo(()=>sortResults(calculateResults(catalog,context),sort),[context,sort]);
function selectMode(next:SelectionMode){setMode(next);if(next==='qh')setScreen('type');if(next==='purpose')setScreen('purpose');if(next==='model')setScreen('model');if(next==='assistant')setDialog('assistant')}
function applyPurpose(preset:PurposePreset){const next={...draft,...preset.context};setDraft(next);setMode('purpose');setScreen('parameters');setNotice(`Выбрано: ${preset.object} · ${preset.medium}. Проверьте предложенные параметры.`)}
function calculate(){setContext(draft);localStorage.setItem('apgs-selection-context',JSON.stringify(draft));const next=calculateResults(catalog,draft);setTab((['recommended','suitable','possible'] as ResultTab[]).find(level=>next.some(p=>p.level===level))||'excluded');setScreen('results');setNotice(`Подбор обновлён: Q ${draft.q} м³/ч, H ${draft.h} м`);window.setTimeout(()=>resultsRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),50)}
function reset(){setDraft(initialContext);setContext(initialContext);localStorage.setItem('apgs-selection-context',JSON.stringify(initialContext));setTab('recommended');setNotice('Параметры сброшены до исходных значений')}
function toggle(id:string){setCompared(current=>{const next=current.includes(id)?current.filter(x=>x!==id):current.length<3?[...current,id]:current;localStorage.setItem('apgs-compared',JSON.stringify(next));if(current.length>=3&&!current.includes(id))setNotice('Можно сравнить не более трёх моделей');return next})}
function openCard(pump:PumpResult){localStorage.setItem('apgs-selection-context',JSON.stringify(context));localStorage.setItem('apgs-selected-pump',JSON.stringify(pump));window.dispatchEvent(new CustomEvent('apgs:open-product',{detail:{productId:pump.id,context}}));const configured=payload.endpoints?.product;if(configured){window.location.href=configured.replace('{xmlId}',encodeURIComponent(pump.id));return}setNotice(`Выбрана ${pump.name}. Для перехода в карточку Bitrix подключит URL по XML_ID ${pump.id}.`)}
function action(value:HeaderAction){if(value==='selection'){setScreen('start');window.scrollTo({top:0,behavior:'smooth'});return}if(value==='catalog'){setNotice('Переход в каталог подключается через настройки Bitrix.');return}setDialog(value)}
function showDetails(pump:PumpResult){setDetails(pump);setDialog('details')}
const scenarioLabel=mode==='qh'?'Q/H':mode==='purpose'?'по назначению':mode==='model'?'по модели':'с помощником';
return <div className="selector-app"><Header compareCount={compared.length} onAction={action}/>{notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{screen==='start'&&<StartScenario onSelect={selectMode}/>} {screen==='purpose'&&<PurposeStep onBack={()=>setScreen('start')} onSelect={applyPurpose}/>} {screen==='model'&&<ModelSearchStep items={items} onBack={()=>setScreen('start')} onOpen={openCard}/>} {screen==='type'&&<PumpTypeStep selected={draft.pumpType} onSelect={pumpType=>setDraft(value=>({...value,pumpType}))} onContinue={()=>setScreen('parameters')}/>} {(screen==='parameters'||screen==='results')&&<><div className="steps"><span className="active"><i>1</i>Рабочая точка и среда</span><span className={screen==='results'?'active':''}><i>2</i>Результаты подбора</span><span><i>3</i>Выбор насоса</span></div><main className="selector-grid"><SelectionForm context={draft} onChange={setDraft} onSubmit={calculate} onReset={reset}/><section className="results-anchor" ref={resultsRef}><ResultsPanel items={items} context={context} tab={tab} sort={sort} compared={compared} onTab={setTab} onSort={setSort} onCompare={toggle} onOpen={openCard} onDetails={showDetails}/></section><RightRail context={context} items={items} compared={compared} onRemove={toggle}/></main><button className="restart" onClick={()=>setScreen('start')}>Изменить сценарий: {scenarioLabel}</button><button className="mobile-select-cta" onClick={calculate}>Подобрать насос</button></>}{dialog&&<div className="dialog-backdrop" onMouseDown={()=>setDialog(null)}><section className="demo-dialog" onMouseDown={event=>event.stopPropagation()}><button className="dialog-close" onClick={()=>setDialog(null)}>×</button><h2>{dialog==='specification'?'Спецификация':dialog==='comparison'?'Сравнение':dialog==='quote'?'Получить КП':dialog==='assistant'?'Инженерный помощник':'Подробности модели'}</h2>{dialog==='comparison'?(compared.length?items.filter(x=>compared.includes(x.id)).map(x=><p key={x.id}><b>{x.name}</b> — {x.score}%</p>):<p>Добавьте насосы к сравнению в результатах.</p>):dialog==='specification'?<p>Спецификация пока пуста. Откройте карточку насоса и добавьте позицию.</p>:dialog==='quote'?<form onSubmit={event=>{event.preventDefault();setDialog(null);setNotice('Заявка на КП сохранена в демо-режиме')}}><input required placeholder="Имя"/><input required placeholder="Телефон"/><button className="button primary">Отправить заявку</button></form>:dialog==='assistant'?<><p>Помощник остаётся отдельной точкой входа. Он уточнит назначение, среду и условия работы, затем передаст параметры в подборщик.</p><button className="button primary" onClick={()=>{setDialog(null);setScreen('purpose')}}>Начать с назначения</button></>:<><p><b>{details?.name}</b></p><p>{details?.exclusionReason||details?.reasons.join(' · ')}</p></>}</section></div>}</div>}
